spring.application.name=demo
# ===============================
# 1. MySQL 資料庫連線設定
# ===============================
# 指定連線到本機的 stock_analysis 資料庫，並強制使用 utf8mb4 與台北時區
spring.datasource.url=jdbc:mysql://localhost:3306/stock_analysis?serverTimezone=Asia/Taipei&useSSL=false&characterEncoding=UTF-8\
  # 你的 MySQL 帳號 (預設通常是 root)
spring.datasource.username=root
# ⚠️ 請填入你安裝 MySQL 時設定的密碼
spring.datasource.password=addie20041124
# 指定 MySQL 的驅動程式
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# 2. JPA & Hibernate 設定 (幫助除錯的好幫手)
# ===============================
# 當 Java 程式碼執行操作時，把底層偷偷產生的 SQL 語法印在終端機上讓我們看
spring.jpa.show-sql=true
# 排版印出來的 SQL，讓它變好看
spring.jpa.properties.hibernate.format_sql=true
# 由於我們已經手動在 Workbench 建好 Table 了，所以設為 none，避免系統雞婆幫我們重建
spring.jpa.hibernate.ddl-auto=none
